import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
} from '@ionic/angular/standalone';
import { IonCol, IonGrid, IonRow } from '@ionic/angular/standalone';
import {
  IonCard,
  IonText,
  IonButton,
  IonButtons,
  IonBackButton,
  IonIcon,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
} from '@ionic/angular/standalone';
import {
  IonItem,
  IonLabel,
  IonImg,
  IonList,
  IonInput,
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  checkmarkCircleOutline,
  checkmarkDoneCircleOutline,
  contract,
  expand,
  eyeOffOutline,
  eyeOutline,
  heart,
  heartOutline,
  lockClosedOutline,
  mailOutline,
  pauseCircle,
  playCircle,
  volumeHigh,
  volumeMute,
} from 'ionicons/icons';

// Add the icons you want to use
addIcons({
  mailOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  playCircle,
  pauseCircle,
  volumeHigh,
  volumeMute,
  expand,
  contract,
  checkmarkCircleOutline,
  heart,
  heartOutline,
  checkmarkDoneCircleOutline,
});
@NgModule({
  declarations: [],

  imports: [
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    IonHeader,
    IonButton,
    IonButtons,
    IonCol,
    IonGrid,
    IonRow,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonItem,
    IonLabel,
    IonList,
    IonInput,
    IonBackButton,
    IonIcon,
    IonImg,
    IonText,
    RouterModule,
    ReactiveFormsModule,
    CommonModule,
    FormsModule,
  ],
  exports: [
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    IonHeader,
    IonButton,
    IonButtons,
    IonCol,
    IonGrid,
    IonRow,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonItem,
    IonLabel,
    IonList,
    IonInput,
    IonBackButton,
    IonIcon,
    IonImg,
    IonText,
    RouterModule,
    ReactiveFormsModule,
    CommonModule,
    FormsModule,
  ],
})
export class SharedModule {}
