import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
} from '@ionic/angular/standalone';
import { IonCol, IonGrid, IonRow } from '@ionic/angular/standalone';
import {
  IonCard,
  IonText,
  IonButton,
  IonButtons,
  IonBackButton,
  IonIcon,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
} from '@ionic/angular/standalone';
import {
  IonItem,
  IonLabel,
  IonImg,
  IonList,
  IonInput,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonAvatar,
  IonBadge,
  IonSpinner,
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  checkmarkCircleOutline,
  checkmarkDoneCircleOutline,
  close,
  contract,
  expand,
  eyeOffOutline,
  eyeOutline,
  happy,
  heart,
  heartOutline,
  home,
  lockClosedOutline,
  mailOutline,
  pauseCircle,
  person,
  play,
  playCircle,
  pricetag,
  sad,
  shareSocialOutline,
  timeOutline,
  volumeHigh,
  volumeMute,
  apertureOutline,
  createOutline,
  trashOutline,
  search,
  closeCircle,
  searchOutline,
  trophy,
  barbell,
  restaurant,
  layers,
  chevronForward
} from 'ionicons/icons';
import { NgxSkeletonLoaderModule } from 'ngx-skeleton-loader';

// Add the icons you want to use
addIcons({
  mailOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  playCircle,
  pauseCircle,
  volumeHigh,
  volumeMute,
  expand,
  contract,
  checkmarkCircleOutline,
  heart,
  heartOutline,
  checkmarkDoneCircleOutline,
  sad,
  happy,
  close,
  pricetag,
  person,
  home,
  timeOutline,
  shareSocialOutline,
  play,
  apertureOutline,
  createOutline,
  trashOutline,
  search,
  closeCircle,
  searchOutline,
  trophy,
  barbell,
  restaurant,
  layers,
  chevronForward
});
@NgModule({
  declarations: [],

  imports: [
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    IonHeader,
    IonButton,
    IonButtons,
    IonCol,
    IonGrid,
    IonRow,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonItem,
    IonLabel,
    IonList,
    IonInput,
    IonBackButton,
    IonIcon,
    IonImg,
    IonText,
    RouterModule,
    ReactiveFormsModule,
    CommonModule,
    FormsModule,
    IonTab,
    IonTabBar,
    IonTabButton,
    IonTabs,
    IonAvatar,
    IonBadge,
    IonSpinner,
    NgxSkeletonLoaderModule
  ],
  exports: [
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    IonHeader,
    IonButton,
    IonButtons,
    IonCol,
    IonGrid,
    IonRow,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonItem,
    IonLabel,
    IonList,
    IonInput,
    IonBackButton,
    IonIcon,
    IonImg,
    IonText,
    RouterModule,
    ReactiveFormsModule,
    CommonModule,
    FormsModule,
    IonTab,
    IonTabBar,
    IonTabButton,
    IonTabs,
    IonAvatar,
    IonBadge,
    IonSpinner,
    NgxSkeletonLoaderModule
  ],
})
export class SharedModule {}
